### PR TITLE
Adding OpenVSP interface

### PR DESCRIPTION
**Pull request by timryanb**
## Purpose
Adding interface for generating OpenAeroStruct VLM surfaces from OpenVSP model.

## Expected time until merged
Week

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
User needs to install OpenVSP python API. 
Tests included in `tests` subdirectory.

## Checklist

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [x] I have added new tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

### CODE REVIEW

**Comment by timryanb** [comment]
The test coverage is failing now because the openvsp-specific tests are being skipped in the CI. An OpenVSP installation will have to be added to the CI for these tests to run.

**Comment by kanekosh** [comment]
Thank you @timryanb, I have a quick question. At the end of the test, we get the following error and warnings:
```
========== 162 passed, 6 skipped, 1342 warnings in 351.05s (0:05:51) ===========
VSPAERO solver not found in /opt/hostedtoolcache/Python/3.8.12/x64/bin.
VSPAERO viewer not found in /opt/hostedtoolcache/Python/3.8.12/x64/bin.
VSPAERO slicer not found in /opt/hostedtoolcache/Python/3.8.12/x64/bin.
Error Code: 5, Desc: GetStringResults::Can't Find Name disk at index 0
```
Do you know if they matter or can we just ignore these? I'm not familiar with VSP so I have no idea.

**Review by kanekosh — DISMISSED** [review]

**Review by eytanadler — APPROVED** [review]
Very cool stuff @timryanb! I made a couple small changes to the docs---other than that it looks good to me. Out of curiosity, is there an easy way to get wing cross sectional geometry out of the VSP model to use for the wingbox shape in Sham's structural model?

**Comment by timryanb** [comment]
Off the top of my head probably... though I don't know the API calls to do it necessarily.
OpenVSP stores information about the airfoil sections used to define a wing, so in theory you could probably access that info through the API.

**Comment by eytanadler** [comment]
> Off the top of my head probably... though I don't know the API calls to do it necessarily. OpenVSP stores information about the airfoil sections used to define a wing, so in theory you could probably access that info through the API.

Ah ok, makes sense. That's a problem for later...

**Pull request merged**
