### PR TITLE
Update aerostruct_groups.py

### PR DESCRIPTION
**Pull request by acmarta**
Promote section lift coefficient distribution, Cl, in surfaces

## Type of change

- [x] Other (please describe)

### CODE REVIEW

**Comment by eytanadler** [comment]
While the tests are running, I have a couple comments:
1. What do we think about also adding `"CDw"` to the promotes while we're at it for consistency @kanekosh?
2. Could you please bump the version in openaerostruct/__init__.py to 2.5.1

**Comment by kanekosh** [comment]
> What do we think about also adding "CDw" to the promotes

That's a good point, could you add that too @acmarta ?

**Comment by acmarta** [comment]
Added "CDw" to the list of promotes

**Comment by eytanadler** [comment]
> Added "CDw" to the list of promotes

Thanks!

> 2. Could you please bump the version in `openaerostruct/__init__.py` to `"2.5.1"`

And this one too @acmarta

**Comment by acmarta** [comment]
Version bumped to 2.5.1

**Comment by eytanadler** [comment]
> Version bumped to 2.5.1

Sorry maybe I should've been more clear, it's fine just to do it in this PR. I'll take care of it and then we can get this merged. Thanks for the contribution!

**Review by eytanadler — APPROVED** [review]

**Pull request merged**
