### PR TITLE
Adding `get_tagged_indices` to mphys wrapper

### PR DESCRIPTION
**Pull request by timryanb**
## Purpose

This is related to https://github.com/OpenMDAO/mphys/pull/158 and https://github.com/smdogroup/funtofem/pull/192 and allows for aerostructural analysis with multiple bodies

## Expected time until merged

a week

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by eytanadler** [comment]
Any idea what is going on with PETSc? It's happening in other builds too, so I don't think it's a change caused by this PR. Do you know of any updates to dependencies? I was going to take a look but I haven't had time to get around to it yet.

Other than that, this looks fine to me. I don't know the mphys side of things, so maybe @bernardopacini has some input. If not, we can merge it once the PETSc problem is sorted.

**Comment by timryanb** [comment]
@eytanadler this is likely a problem with Cython 3.0 which was released recently released. There seems to be issue mentioning this on the petsc4py repo: https://gitlab.com/petsc/petsc/-/issues/1423. You might want to try pip installing cython 0.29 before installing petsc4py. We had a similar issue on TACS that @A-CGray discovered, he may have some other ideas

**Comment by A-CGray** [comment]
Yeah PETSc4py is the issue here, we fixed this in our docker builds by pip installing `"cython<3.0"`. In the longer term though, why don't we just run these actions on one of our docker containers?

**Comment by eytanadler** [comment]
Thanks! For some reason that happens periodically. We tried updating the codecov action to the newest but it doesn't always work. I triggered the tests again to see if it'll work the second time.

**Review by eytanadler — APPROVED** [review]
Looks good to me. Let's wait on Ali before merging though.

**Comment by A-CGray** [comment]
@timryanb can you bump the version to 2.7.0 as this PR introduces a new backwards compatible feature. I would do it but can't push to your fork

**Comment by timryanb** [comment]
I'm happy to do so @A-CGray, though the feature should be backwards-compatible for the record

**Comment by timryanb** [comment]
@eytanadler is it alright to do the version bump in this PR or is it easier a new PR dedicated to the bump after this PR?

**Comment by A-CGray** [comment]
> I'm happy to do so @A-CGray, though the feature should be backwards-compatible (non-breaking) for the record

Yep, that's why I want to bump the minor version and not the major version. I don't think we have a consistent rule for this stuff but I try to follow the semantic versioning rules:
image

**Comment by timryanb** [comment]
> > I'm happy to do so @A-CGray, though the feature should be backwards-compatible (non-breaking) for the record
> 
> Yep, that's why I want to bump the minor version and not the major version. I don't think we have a consistent rule for this stuff but I try to follow the semantic versioning rules: image

Ah sorry, missed the "backwards **compatible**" comment...

**Comment by eytanadler** [comment]
Let's lump the minor version change in with #413. Feel free to update the version number here, but let's not make a new release yet.

**Review by A-CGray — APPROVED** [review]

**Pull request merged**
