### PR TITLE
Updating MPhys wrapper for 2.0 update

### PR DESCRIPTION
**Pull request by timryanb**
## Purpose
Refactored builder class to use new mphys import procedures and variable naming convention. MPhys 2.0 has officially been released, so this PR is ready to be merged in. This is a backwards-incompatible change for the MPhys wrapper, so I'd recommend making a version bump after this PR. 

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by timryanb** [comment]
It looks like the CI tests are failing due to the fact that MPhys 1.1.0 is pinned in the Azure pipeline. Is there a way to update this when MPhys 2.0 is released @A-CGray?

**Comment by A-CGray** [comment]
> It looks like the CI tests are failing due to the fact that MPhys 1.1.0 is pinned in the Azure pipeline. Is there a way to update this when MPhys 2.0 is released @A-CGray?

Ah yeah, this is kind of a pain, we probably won't update the docker images that the CI jobs use to MPhys 2 until our other codes like ADflow and pyGeo are MPhys 2 compatible. In the meantime, I've added a line to the script that install OpenAeroStruct in the CI jobs that removes the pip constraint on the mphys version so that it can install mphys 2 itself.

**Review by kanekosh — CHANGES_REQUESTED** [review]
Thank you, Tim!
I believe `integration_tests/test_simple_rect_mphys_aero.py` and `test_simple_rect_mphys_aero_compressible.py` also need to be updated. These tests are currently skipped (rather than tests being failed) as a result of failed Mphys import.

**Comment by timryanb** [comment]
> Thank you, Tim! I believe `integration_tests/test_simple_rect_mphys_aero.py` and `test_simple_rect_mphys_aero_compressible.py` also need to be updated. These tests are currently skipped (rather than tests being failed) as a result of failed Mphys import.

Good catch @kanekosh, should be fixed now

**Pull request merged**
