### PR TITLE
 AURORA modifications 1: Added component to compute aero forces at panel nodes.

### PR DESCRIPTION
**Pull request by Kenneth-T-Moore**
Code originally from timryanb of Aurora Flight Sciences. Migrated with the following modifications: added test, sparsified derivatives, eliminated looping, made le and te weight values user-settable as options, modified so a single component works on all surfaces.

Also added an egg_info directory to the git ignore.

### CODE REVIEW

**Comment by johnjasa** [comment]
This pull request **introduces 3 alerts** when merging 80d959a09d17ae585eda931332aaed3c8fefad7a into 0426146306e11b0965058dad0b0d973457f2e55f - [view on LGTM.com](https://lgtm.com/projects/g/mdolab/OpenAeroStruct/rev/pr-9587e8d5c8a4632adc84e6986544e92e07eb09db)

**new alerts:**

* 2 for Unused local variable
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Kenneth-T-Moore** [comment]
Or maybe just aero_mesh_points?  I know it's a little long, but at least there is no confusion.

**Comment by johnjasa** [comment]
That's a great name. Could you please change these instances to that?

**Comment by Kenneth-T-Moore** [comment]
Name changed to mesh_point (so MeshPointForces now.)

**Comment by johnjasa** [comment]
This pull request **introduces 3 alerts** when merging d64468988d7c25596a1b2a06392a0705ae98ec73 into 0426146306e11b0965058dad0b0d973457f2e55f - [view on LGTM.com](https://lgtm.com/projects/g/mdolab/OpenAeroStruct/rev/pr-69f53bdbfc0355d5e490fe7fd5277570d83dad30)

**new alerts:**

* 2 for Unused local variable
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
