### PR TITLE
Fixed random seeds

### PR DESCRIPTION
**Pull request by kanekosh**
## Purpose
Fixed all random seeds so that all tests will be reproducible. Also, replaced `np.random.seed()`with `np.random.default_rng()`, which is a new best practice.

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Checklist

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by eytanadler** [comment]
Thanks for the quick update Shugo! I remember Ali went through a similar problem with TACS and [his solution](https://github.com/mdolab/tacs_orig/blob/90fec188483b5cf5770e7c5f651aa6b30d429d6a/tests/test_elements.py#L108) was to set the random seed in the setup method for each test case class like this:

```python
class SampleTestCase(unittest.TestCase):
    def setUp(self):
        np.random.seed(100)
    def test_one(self):
        ...
    def test_two(self):
        ...
    ...
```

I think it might be a cleaner solution since it avoids having to set it in each test case method (the `setUp` method is called before each test case method). What do you think?

**Comment by kanekosh** [comment]
I might be wrong, but if we set a single seed (either using `np.random.seed` or `default_rng`) for each class in the setup method, the random input values generated in each method will depend on the order of execution within each class (i.e., whether the testflo runs `test_one()` first, or `test_two()` first).
I was not confident if the test methods are executed in a deterministic order (especially when parallelizing the test), that's why I hardcoded the test within each method.

**Comment by eytanadler** [comment]
Ali and I were wondering the same thing, but it turns out that `setUp` is run before every test method, not just once for each class. The [documentation](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUp) says something vaguely like that, and the example at the bottom of [this page](https://www.codingame.com/playgrounds/10614/python-unit-test-with-unittest) confirms it.

**Comment by kanekosh** [comment]
Thanks Eytan, I didn't know that `setUp` is called every time. I'll fix it soon.

**Comment by nwu63** [comment]
It's explained a bit earlier in the docs:
```
The setUp() and tearDown() methods allow you to define instructions that will be executed before and after each test method.
```

**Comment by kanekosh** [comment]
Addressed Eytan's suggestion

**Review by nwu63 — APPROVED** [review]
LGTM

**Comment by nwu63** [comment]
I'm guessing the docs build failure is due to #376 not merged? Should we merge this PR despite the failure?

**Comment by eytanadler** [comment]
Yup, the MDO Lab's RTD is trying to build without actually having the files to tell it which modules to install. Thanks again, Shugo!

**Pull request merged**
