### PR TITLE
Removed old docs in Github Pages

### PR DESCRIPTION
**Pull request by kanekosh**
## Purpose
Removed old docs hosted on Github Pages, and added an html to redirect visitors to the new docs.
Please see `index.html` for the actual change; all the other files are just deleted.

After merging this, the old documentation link https://mdolab.engin.umich.edu/OpenAeroStruct/ will redirect to the new link https://mdolab-openaerostruct.readthedocs-hosted.com/en/latest/.
Click [here](https://kanekosh.github.io/OpenAeroStruct/) to check what will happen. This is my local deployment of the new html (for testing purpose).

 

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

### CODE REVIEW

**Review by lamkina — APPROVED** [review]
I think this all looks good.  Just a general question, will there be anything we need to with google to make sure the RTD link is the top search result?  I don't think it will matter since you are re-directing the link, but I'm just curious.

**Review by nwu63 — APPROVED** [review]
LGTM

**Comment by kanekosh** [comment]
I tried submitting a request to Google (https://support.google.com/webmasters/answer/7041154?hl=en), but I'm not sure if this works because our old page technically still exists.

**Comment by lamkina** [comment]
I'm sure it's fine regardless!

**Pull request merged**
