### PR TITLE
Add ground effect

### PR DESCRIPTION
**Pull request by bbrelje**
## Purpose
This PR implements ground effect in the VLM methods as well as adding a theory documentation page.

I also simplified the derivative sparsity patterns in the AIC matrix calculation to make them a little bit less arcane.

I made a minor change to the contributor docs to teach how to build on windows

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- New feature (non-breaking change which adds functionality)
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
- Documentation update

## Testing
I am passing the local reg tests and I added new component and integration tests of my own for the new feature.

## Checklist
_Put an `x` in the boxes that apply._

- [X ] I have run unit and regression tests which pass locally with my changes
- [X] I have added new tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation

### CODE REVIEW

**Comment by nwu63** [comment]
It's been a while since I've looked at OAS, so if you have time @kanekosh it might be better for you to review -- let me know how I can support that.

Also, do we want to make a new patch release before merging this? IMO this might be enough to warrant a new minor release after.

**Comment by bbrelje** [comment]
Don't merge this yet. I killed the performance of the setup method for the AIC calculation with this beauty:
https://github.com/bbrelje/OpenAeroStruct/blob/b5944f03f7962d15068a3faa0e3af35104725497/openaerostruct/aerodynamics/eval_mtx.py#L231

Turns out doing a brute force search for repeated jacobian indices in the symmetric case is more _readable_ than whatever cute trick was in there before but not performant!

**Comment by nwu63** [comment]
Right, yeah feel free to mark the PR as draft which will automatically block merging.

**Comment by bbrelje** [comment]
OK, this one is ready to go now. I checked performance on a big problem and it's as good as the original now. 

The setup() method of the AIC assembly step is still taking quite a while but it's not intractable. I'll open an issue.

**Comment by kanekosh** [comment]
Looks good, just added a few comments in eval_mtx, as well as the mode print output in `assert_check_totals`.
Please ignore a bunch of irrelevant commits, it was a branch confusion, sorry about that.

**Review by kanekosh — APPROVED** [review]

**Comment by nwu63** [comment]
Please don't merge this yet -- let me fix release v2.2.2 first (the version was not incremented in the init file).

**Comment by nwu63** [comment]
All good now. If anyone is planning to make another release after this you could bump the version here.

**Comment by bernardopacini** [comment]
This looks good to me. @bbrelje do you want this to be a new release? I will hold off on merging until you've decided.

**Review by bernardopacini — DISMISSED** [review]

**Comment by bbrelje** [comment]
Given that it's a pretty significant refactoring of the AIC component I think it warrants a new release

**Review by kanekosh — APPROVED** [review]

**Pull request merged**
