### PR TITLE
Bug fixed in load transfer scheme

### PR DESCRIPTION
**Pull request by kanekosh**
## Purpose
This PR is to fix the issue #314. The load transfer scheme was fixed so that it is now consistent with the formulas presented in the journal paper `Jasa2018a`. Further details about the bug can be found in #314.  
Once approved, a new version 2.2.1 should be released.

I updated the followings:
- Load transfer computation and its partial derivatives
- Reference values of all aerostructural regression tests
- Documentation (not related to the bug): n2 diagram from the latest OpenMDAO 3.1.1

## Type of change

- Bugfix (non-breaking change which fixes an issue)
- Documentation update

## Testing
- To verify the new load transfer implementation, Sham and I performed mesh refinement studies that compare the new and old codes. We confirmed that differences in both AS analysis and optimization are small enough for reasonably fine meshes (details in #314). 
- Partial derivatives implementation was verified by the load transfer unit test, which calls OpenMDAO's `check_partials()`. 

## Checklist

- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by nwu63** [comment]
I don't have a lot of experience with this stuff so I'll defer to Sham and John. For that one failed test, is it related to this PR? I'm wondering if we should retrain the reference value instead of just relaxing the tolerance.

**Comment by kanekosh** [comment]
Yes, the failed test was about this PR. The relative error was slightly above `1.e-5` for one of the optimization tests. Though I haven't confirmed, I think it was because of the version difference of a `scipy` optimizer between my local and Travis build.

**Comment by nwu63** [comment]
Oh sorry I got confused, I thought you only changed the tolerance, but in fact you had already re-trained the values, but it somehow failed on Travis, due to some discrepancy between Travis and your local machine. Understood, I'm fine with this PR then.

**Comment by shamsheersc19** [comment]
> @johnjasa and @shamsheersc19 do you feel that this deserves a minor version increment instead of a bugfix release?

@nwu63 I think this deserves a minor version increment.

**Comment by nwu63** [comment]
> @nwu63 I think this deserves a minor version increment.

If that is the case, then please increment the version and make a new release. I think @kanekosh should do this since he did the PR. Feel free to message me if you have any questions on how you should do this.

**Comment by shamsheersc19** [comment]
> If that is the case, then please increment the version and make a new release. I think @kanekosh should do this since he did the PR. Feel free to message me if you have any questions on how you should do this.

I misunderstood the versioning terminology. Proceeding with a patch release. Thanks!

**Pull request merged**
